# helm install cns oci://mcr.microsoft.com/cns/cns --version 2.0.0-alpha.nvidia.2 --create-namespace --namespace cns-system --wait --atomic --values cns-values.yaml
clusterConfig:
  configYaml: |-
    apiVersion: containerstorage.azure.com/v1
    kind: ClusterConfig
    enableInstallerStrictMode: true
    enableElasticSan: true
    enableNvmeDisk: true
    enableStriping: true
    enableEphemeralBypassAnnotation: true
    agentImage: mcr.microsoft.com/cns/agent:2.0.0-alpha.nvidia.2
    agentTolerations:
    - key: "sku"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "userpool"
      effect: "NoSchedule"